# Builds detectorModel.py: character-bigram log-likelihood-ratio tables
# (legacy-font text vs English) used by the add-on's detector.
# Training data: wordfreq English and Hindi word lists (Hindi Devanagari words are
# re-encoded to Preeti and Kruti Dev), plus the Nepali sample sentences.
import sys, math, collections, unicodedata, random, json
sys.path.insert(0, "addon/globalPlugins/nepaliReader")
import legacyFonts as LF
import wordfreq
from npttf2utf.base.preetimapper import convert as toPreeti

random.seed(1)
N = lambda s: unicodedata.normalize("NFC", s)

# ---- Unicode -> Kruti Dev (training only) ----
inv = {}
for k, v in LF._KRUTI_MAIN:
	if any(c in k for c in "fZ") or not v or not all("ऀ" <= c <= "ॿ" for c in v):
		continue
	if v not in inv or len(k) < len(inv[v]):
		inv[v] = k
keysByLen = sorted(inv, key=len, reverse=True)


def toKruti(u):
	out = []
	i = 0
	while i < len(u):
		reph = False
		if u.startswith("र्", i) and i + 2 < len(u) and u[i + 2] in LF.CONSONANTS:
			reph = True
			i += 2
		if u[i] in LF.CONSONANTS:
			end = LF._clusterEnd(u, i)
			cl = u[i:end]
			if end < len(u) and u[end] == LF.HALANT:
				cl += LF.HALANT
				end += 1
			signs = ""
			while end < len(u) and u[end] in LF.SIGNS:
				signs += u[end]
				end += 1
			enc = ""
			j = 0
			while j < len(cl):
				for key in keysByLen:
					if cl.startswith(key, j):
						enc += inv[key]
						j += len(key)
						break
				else:
					return None
			pre = ""
			if "ि" in signs:
				pre = "f"
				signs = signs.replace("ि", "")
			tail = ""
			j = 0
			while j < len(signs):
				for key in keysByLen:
					if signs.startswith(key, j):
						tail += inv[key]
						j += len(key)
						break
				else:
					return None
			out.append(pre + enc + tail + ("Z" if reph else ""))
			i = end
		else:
			for key in keysByLen:
				if u.startswith(key, i):
					out.append(inv[key])
					i += len(key)
					break
			else:
				return None
	return "".join(out)


ALPHA = [chr(c) for c in range(33, 127)]
BOS, EOS = "^", "$"


def bigrams(w):
	s = BOS + w + EOS
	return [s[i:i + 2] for i in range(len(s) - 1)]


def counts(weighted):
	c = collections.Counter()
	for w, f in weighted:
		for b in bigrams(w):
			c[b] += f
	return c


def logprobs(c, k=0.5):
	# conditional P(b|a) with add-k smoothing
	ctx = collections.Counter()
	for b, n in c.items():
		ctx[b[0]] += n
	V = len(ALPHA) + 1
	res = {}
	for a in [BOS] + ALPHA:
		tot = ctx[a] + k * V
		for b in ALPHA + [EOS]:
			res[a + b] = math.log((c.get(a + b, 0) + k) / tot)
	return res


def keepAscii(w):
	return all(32 < ord(ch) < 127 for ch in w)


en = wordfreq.top_n_list("en", 60000)
enW = [(w, wordfreq.word_frequency(w, "en") * 1e6 + 1) for w in en if keepAscii(w)]
# English text also has Capitalised words
enW += [(w.capitalize(), f * 0.3) for w, f in enW[:20000]]

hi = [w for w in wordfreq.top_n_list("hi", 40000) if all("ऀ" <= c <= "ॿ" for c in w) and "़" not in w]
neSent = [w for line in open("tests/sentences_ne.txt", encoding="utf8") for w in line.split()]
preW, kruW = [], []
for w in hi[:20000] + neSent * 20:
	f = wordfreq.word_frequency(w, "hi") * 1e6 + 1
	p = toPreeti(w)
	if keepAscii(p) and N(LF.preetiFamilyToUnicode(p)) == N(w):
		preW.append((p, f))
	k = toKruti(w)
	if k and keepAscii(k) and N(LF.krutiDevToUnicode(k)) == N(w):
		kruW.append((k, f))
print("training words: en", len(enW), "preeti", len(preW), "kruti", len(kruW))

E = logprobs(counts(enW))
model = {}
for name, data in (("preeti", preW), ("kruti", kruW)):
	L = logprobs(counts(data))
	model[name] = {b: round(L[b] - E[b], 2) for b in L if abs(L[b] - E[b]) > 0.05}

with open("addon/globalPlugins/nepaliReader/detectorModel.py", "w", encoding="utf8") as f:
	f.write("# Generated by tools/train_detector.py - character bigram log-likelihood ratios\n")
	f.write("# (legacy encoding vs English). Derived from wordfreq statistics.\n")
	f.write("MODEL = " + json.dumps(model, separators=(",", ":")) + "\n")

# held-out evaluation material
json.dump({"preeti": [w for w, _ in preW[::7]], "kruti": [w for w, _ in kruW[::7]],
	"hiHeldPreeti": [toPreeti(w) for w in wordfreq.top_n_list("hi", 100000)[20000:] if all("ऀ" <= c <= "ॿ" for c in w)],
	"hiHeldKruti": [x for x in (toKruti(w) for w in wordfreq.top_n_list("hi", 100000)[20000:]) if x],
	"enHeld": [w for w in wordfreq.top_n_list("en", 100000)[60000:] if keepAscii(w)]},
	open("tests/heldout.json", "w"))
print("done")
